import Handlebars from 'handlebars';
import type { ServerDocData } from './markdown-generator.js';

const HTML_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{serverName}} Documentation</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a2e; background: #f8f9fa; line-height: 1.6; }
    .container { max-width: 960px; margin: 0 auto; padding: 2rem; }
    h1 { font-size: 2rem; margin-bottom: 0.5rem; color: #2D5A27; }
    h2 { font-size: 1.5rem; margin: 2rem 0 1rem; border-bottom: 2px solid #e0e0e0; padding-bottom: 0.5rem; }
    h3 { font-size: 1.15rem; margin: 1.5rem 0 0.5rem; }
    .version { color: #666; font-size: 1rem; font-weight: normal; }
    .tool-card { background: #fff; border: 1px solid #e0e0e0; border-radius: 8px; padding: 1rem 1.25rem; margin-bottom: 1rem; }
    .tool-card h3 { margin-top: 0; }
    .tool-card p { color: #555; margin-bottom: 0.75rem; }
    pre { background: #1e1e2e; color: #cdd6f4; padding: 1rem; border-radius: 6px; overflow-x: auto; font-size: 0.85rem; }
    code { font-family: 'SF Mono', 'Fira Code', monospace; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { text-align: left; padding: 0.5rem 0.75rem; border: 1px solid #e0e0e0; }
    th { background: #f1f3f5; font-weight: 600; }
    .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e0e0e0; color: #888; font-size: 0.85rem; }
  </style>
</head>
<body>
  <div class="container">
    <h1>{{serverName}} {{#if serverVersion}}<span class="version">v{{serverVersion}}</span>{{/if}}</h1>

    <h2>Tools</h2>
    {{#if tools.length}}
    {{#each tools}}
    <div class="tool-card">
      <h3>{{this.name}}</h3>
      {{#if this.description}}<p>{{this.description}}</p>{{/if}}
      {{#if this.inputSchema}}
      <strong>Input Schema:</strong>
      <pre><code>{{jsonPretty this.inputSchema}}</code></pre>
      {{/if}}
    </div>
    {{/each}}
    {{else}}
    <p>No tools available.</p>
    {{/if}}

    {{#if resources.length}}
    <h2>Resources</h2>
    <table>
      <thead>
        <tr><th>URI</th><th>Name</th><th>Description</th><th>MIME Type</th></tr>
      </thead>
      <tbody>
        {{#each resources}}
        <tr>
          <td>{{this.uri}}</td>
          <td>{{or this.name "-"}}</td>
          <td>{{or this.description "-"}}</td>
          <td>{{or this.mimeType "-"}}</td>
        </tr>
        {{/each}}
      </tbody>
    </table>
    {{/if}}

    <div class="footer">
      Generated by MCPSpec on {{generatedAt}}
    </div>
  </div>
</body>
</html>`;

export class HtmlDocGenerator {
  private template: HandlebarsTemplateDelegate;

  constructor() {
    Handlebars.registerHelper('jsonPretty', (obj: unknown) => {
      return new Handlebars.SafeString(JSON.stringify(obj, null, 2));
    });
    Handlebars.registerHelper('or', (a: unknown, b: unknown) => a || b);
    this.template = Handlebars.compile(HTML_TEMPLATE);
  }

  generate(data: ServerDocData): string {
    return this.template({
      ...data,
      generatedAt: data.generatedAt.toISOString(),
    });
  }
}
