import type { ToolInfo, ResourceInfo } from '../client/mcp-client-interface.js';

export interface ServerDocData {
  serverName: string;
  serverVersion?: string;
  tools: ToolInfo[];
  resources: ResourceInfo[];
  generatedAt: Date;
}

export class MarkdownGenerator {
  generate(data: ServerDocData): string {
    const lines: string[] = [];

    // Header
    const version = data.serverVersion ? ` v${data.serverVersion}` : '';
    lines.push(`# ${data.serverName}${version}`);
    lines.push('');

    // Tools section
    if (data.tools.length > 0) {
      lines.push('## Tools');
      lines.push('');
      lines.push('| Name | Description |');
      lines.push('|------|-------------|');
      for (const tool of data.tools) {
        const desc = tool.description ?? '-';
        lines.push(`| ${tool.name} | ${desc} |`);
      }
      lines.push('');

      // Per-tool detail sections
      for (const tool of data.tools) {
        lines.push(`### ${tool.name}`);
        lines.push('');
        if (tool.description) {
          lines.push(tool.description);
          lines.push('');
        }
        if (tool.inputSchema) {
          lines.push('**Input Schema:**');
          lines.push('');
          lines.push('```json');
          lines.push(JSON.stringify(tool.inputSchema, null, 2));
          lines.push('```');
          lines.push('');
        }
      }
    } else {
      lines.push('## Tools');
      lines.push('');
      lines.push('No tools available.');
      lines.push('');
    }

    // Resources section
    if (data.resources.length > 0) {
      lines.push('## Resources');
      lines.push('');
      lines.push('| URI | Name | Description | MIME Type |');
      lines.push('|-----|------|-------------|-----------|');
      for (const res of data.resources) {
        const name = res.name ?? '-';
        const desc = res.description ?? '-';
        const mime = res.mimeType ?? '-';
        lines.push(`| ${res.uri} | ${name} | ${desc} | ${mime} |`);
      }
      lines.push('');
    }

    // Footer
    lines.push('---');
    lines.push('');
    lines.push(`*Generated by MCPSpec on ${data.generatedAt.toISOString()}*`);
    lines.push('');

    return lines.join('\n');
  }
}
