import type { TestResult, TestRunResult } from '@mcpspec/shared';
import type { TestRunReporter } from '../test-runner.js';
import type { SecretMasker } from '../../utils/secret-masker.js';
import Handlebars from 'handlebars';

const HTML_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MCPSpec Test Report - {{collectionName}}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; color: #333; padding: 24px; }
  .container { max-width: 960px; margin: 0 auto; }
  h1 { font-size: 24px; margin-bottom: 16px; }
  .summary { display: flex; gap: 16px; margin-bottom: 24px; flex-wrap: wrap; }
  .card { background: #fff; border-radius: 8px; padding: 16px 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  .card .label { font-size: 12px; color: #888; text-transform: uppercase; }
  .card .value { font-size: 28px; font-weight: 700; }
  .passed .value { color: #22c55e; }
  .failed .value { color: #ef4444; }
  .errors .value { color: #f97316; }
  .duration .value { color: #3b82f6; }
  table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  th { background: #f9fafb; text-align: left; padding: 12px 16px; font-size: 12px; text-transform: uppercase; color: #888; border-bottom: 1px solid #e5e7eb; }
  td { padding: 12px 16px; border-bottom: 1px solid #f3f4f6; vertical-align: top; }
  tr:last-child td { border-bottom: none; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
  .badge-passed { background: #dcfce7; color: #166534; }
  .badge-failed { background: #fee2e2; color: #991b1b; }
  .badge-error { background: #ffedd5; color: #9a3412; }
  .badge-skipped { background: #fef9c3; color: #854d0e; }
  .assertions { font-size: 13px; color: #666; margin-top: 4px; }
  .assertion-fail { color: #ef4444; }
  .footer { margin-top: 24px; font-size: 12px; color: #aaa; text-align: center; }
</style>
</head>
<body>
<div class="container">
  <h1>MCPSpec: {{collectionName}}</h1>
  <div class="summary">
    <div class="card passed"><div class="label">Passed</div><div class="value">{{summary.passed}}</div></div>
    <div class="card failed"><div class="label">Failed</div><div class="value">{{summary.failed}}</div></div>
    <div class="card errors"><div class="label">Errors</div><div class="value">{{summary.errors}}</div></div>
    <div class="card duration"><div class="label">Duration</div><div class="value">{{durationFormatted}}</div></div>
  </div>
  <table>
    <thead><tr><th>Test</th><th>Status</th><th>Duration</th><th>Details</th></tr></thead>
    <tbody>
      {{#each results}}
      <tr>
        <td>{{this.testName}}</td>
        <td><span class="badge badge-{{this.status}}">{{this.status}}</span></td>
        <td>{{this.duration}}ms</td>
        <td>
          {{#if this.error}}<div class="assertion-fail">{{this.error}}</div>{{/if}}
          {{#each this.assertions}}
            {{#unless this.passed}}<div class="assertion-fail">{{this.message}}</div>{{/unless}}
          {{/each}}
          {{#if this.allPassed}}<span style="color:#22c55e">All assertions passed</span>{{/if}}
        </td>
      </tr>
      {{/each}}
    </tbody>
  </table>
  <div class="footer">Generated by MCPSpec at {{timestamp}}</div>
</div>
</body>
</html>`;

export class HtmlReporter implements TestRunReporter {
  private output: string | undefined;
  private secretMasker: SecretMasker | undefined;

  constructor(private readonly outputPath?: string) {}

  setSecretMasker(masker: SecretMasker): void {
    this.secretMasker = masker;
  }

  onRunStart(_collectionName: string, _testCount: number): void {}
  onTestStart(_testName: string): void {}
  onTestComplete(_result: TestResult): void {}

  onRunComplete(result: TestRunResult): void {
    const template = Handlebars.compile(HTML_TEMPLATE);

    const data = {
      collectionName: result.collectionName,
      summary: result.summary,
      durationFormatted: `${(result.duration / 1000).toFixed(2)}s`,
      timestamp: result.completedAt.toISOString(),
      results: result.results.map((r) => ({
        testName: r.testName,
        status: r.status,
        duration: r.duration,
        error: r.error ? this.mask(r.error) : undefined,
        assertions: r.assertions.map((a) => ({
          passed: a.passed,
          message: this.mask(a.message),
        })),
        allPassed: r.assertions.every((a) => a.passed) && !r.error,
      })),
    };

    const html = template(data);

    if (this.outputPath) {
      this.output = html;
    } else {
      console.log(html);
    }
  }

  getOutput(): string | undefined {
    return this.output;
  }

  private mask(text: string): string {
    return this.secretMasker ? this.secretMasker.mask(text) : text;
  }
}
