import { describe, it, expect } from 'vitest';
import { MarkdownGenerator } from '../../src/documentation/markdown-generator.js';
import { HtmlDocGenerator } from '../../src/documentation/html-generator.js';
import { DocGenerator } from '../../src/documentation/doc-generator.js';
import type { ServerDocData } from '../../src/documentation/markdown-generator.js';
import { MockMCPClient } from '../fixtures/mock-mcp-client.js';

const sampleData: ServerDocData = {
  serverName: 'test-server',
  serverVersion: '2.0.0',
  tools: [
    {
      name: 'read_file',
      description: 'Reads a file from the filesystem',
      inputSchema: {
        type: 'object',
        properties: { path: { type: 'string' } },
        required: ['path'],
      },
    },
    {
      name: 'write_file',
      description: 'Writes content to a file',
      inputSchema: {
        type: 'object',
        properties: { path: { type: 'string' }, content: { type: 'string' } },
        required: ['path', 'content'],
      },
    },
  ],
  resources: [
    {
      uri: 'file:///tmp/test.txt',
      name: 'test.txt',
      description: 'A test file',
      mimeType: 'text/plain',
    },
  ],
  generatedAt: new Date('2026-01-01T00:00:00Z'),
};

describe('MarkdownGenerator', () => {
  const generator = new MarkdownGenerator();

  it('produces valid markdown with tool tables', () => {
    const md = generator.generate(sampleData);
    expect(md).toContain('# test-server v2.0.0');
    expect(md).toContain('## Tools');
    expect(md).toContain('| read_file |');
    expect(md).toContain('| write_file |');
    expect(md).toContain('| Name | Description |');
  });

  it('includes per-tool schema blocks', () => {
    const md = generator.generate(sampleData);
    expect(md).toContain('### read_file');
    expect(md).toContain('**Input Schema:**');
    expect(md).toContain('```json');
    expect(md).toContain('"type": "object"');
  });

  it('includes resources table', () => {
    const md = generator.generate(sampleData);
    expect(md).toContain('## Resources');
    expect(md).toContain('| file:///tmp/test.txt |');
    expect(md).toContain('text/plain');
  });

  it('handles empty tools and resources', () => {
    const md = generator.generate({
      ...sampleData,
      tools: [],
      resources: [],
    });
    expect(md).toContain('No tools available.');
    expect(md).not.toContain('## Resources');
  });

  it('includes generation timestamp footer', () => {
    const md = generator.generate(sampleData);
    expect(md).toContain('Generated by MCPSpec on 2026-01-01T00:00:00.000Z');
  });

  it('handles tools without description', () => {
    const md = generator.generate({
      ...sampleData,
      tools: [{ name: 'bare_tool' }],
    });
    expect(md).toContain('| bare_tool | - |');
  });
});

describe('HtmlDocGenerator', () => {
  const generator = new HtmlDocGenerator();

  it('produces valid HTML containing tool names', () => {
    const html = generator.generate(sampleData);
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('read_file');
    expect(html).toContain('write_file');
  });

  it('contains schema code blocks', () => {
    const html = generator.generate(sampleData);
    expect(html).toContain('<pre>');
    expect(html).toContain('"type": "object"');
  });

  it('contains resource table', () => {
    const html = generator.generate(sampleData);
    expect(html).toContain('file:///tmp/test.txt');
    expect(html).toContain('text/plain');
  });
});

describe('DocGenerator', () => {
  it('introspects server and returns correct data', async () => {
    const client = new MockMCPClient({
      tools: [{ name: 'tool1', description: 'A tool' }],
      resources: [{ uri: 'file:///a', name: 'a' }],
      serverInfo: { name: 'my-server', version: '3.0.0' },
    });
    await client.connect();

    const generator = new DocGenerator();
    const data = await generator.introspect(client);

    expect(data.serverName).toBe('my-server');
    expect(data.serverVersion).toBe('3.0.0');
    expect(data.tools).toHaveLength(1);
    expect(data.resources).toHaveLength(1);
    expect(data.generatedAt).toBeInstanceOf(Date);
  });

  it('generates markdown by format', async () => {
    const client = new MockMCPClient({
      tools: [{ name: 'tool1' }],
      serverInfo: { name: 'my-server' },
    });
    await client.connect();

    const generator = new DocGenerator();
    const content = await generator.generate(client, { format: 'markdown' });
    expect(content).toContain('# my-server');
    expect(content).toContain('## Tools');
  });

  it('generates HTML by format', async () => {
    const client = new MockMCPClient({
      tools: [{ name: 'tool1' }],
      serverInfo: { name: 'my-server' },
    });
    await client.connect();

    const generator = new DocGenerator();
    const content = await generator.generate(client, { format: 'html' });
    expect(content).toContain('<!DOCTYPE html>');
    expect(content).toContain('tool1');
  });

  it('handles listResources failure gracefully', async () => {
    const client = new MockMCPClient({
      tools: [{ name: 'tool1' }],
      serverInfo: { name: 'my-server' },
    });
    // Override listResources to throw
    client.listResources = async () => { throw new Error('Not supported'); };
    await client.connect();

    const generator = new DocGenerator();
    const data = await generator.introspect(client);
    expect(data.resources).toHaveLength(0);
  });
});
