export type ErrorCode =
  | 'CONNECTION_TIMEOUT'
  | 'CONNECTION_REFUSED'
  | 'CONNECTION_LOST'
  | 'PROCESS_SPAWN_FAILED'
  | 'PROCESS_CRASHED'
  | 'PROCESS_TIMEOUT'
  | 'TOOL_NOT_FOUND'
  | 'TOOL_CALL_FAILED'
  | 'INVALID_RESPONSE'
  | 'SCHEMA_VALIDATION_FAILED'
  | 'ASSERTION_FAILED'
  | 'COLLECTION_PARSE_ERROR'
  | 'COLLECTION_VALIDATION_ERROR'
  | 'YAML_PARSE_ERROR'
  | 'YAML_TOO_LARGE'
  | 'YAML_TOO_DEEP'
  | 'TIMEOUT'
  | 'RATE_LIMITED'
  | 'CONFIG_ERROR'
  | 'NOT_IMPLEMENTED'
  | 'UNKNOWN_ERROR';

import { EXIT_CODES } from '@mcpspec/shared';

export const ERROR_CODE_MAP: Record<ErrorCode, number> = {
  CONNECTION_TIMEOUT: EXIT_CODES.CONNECTION_ERROR,
  CONNECTION_REFUSED: EXIT_CODES.CONNECTION_ERROR,
  CONNECTION_LOST: EXIT_CODES.CONNECTION_ERROR,
  PROCESS_SPAWN_FAILED: EXIT_CODES.ERROR,
  PROCESS_CRASHED: EXIT_CODES.ERROR,
  PROCESS_TIMEOUT: EXIT_CODES.TIMEOUT,
  TOOL_NOT_FOUND: EXIT_CODES.ERROR,
  TOOL_CALL_FAILED: EXIT_CODES.ERROR,
  INVALID_RESPONSE: EXIT_CODES.ERROR,
  SCHEMA_VALIDATION_FAILED: EXIT_CODES.VALIDATION_ERROR,
  ASSERTION_FAILED: EXIT_CODES.TEST_FAILURE,
  COLLECTION_PARSE_ERROR: EXIT_CODES.CONFIG_ERROR,
  COLLECTION_VALIDATION_ERROR: EXIT_CODES.CONFIG_ERROR,
  YAML_PARSE_ERROR: EXIT_CODES.CONFIG_ERROR,
  YAML_TOO_LARGE: EXIT_CODES.CONFIG_ERROR,
  YAML_TOO_DEEP: EXIT_CODES.CONFIG_ERROR,
  TIMEOUT: EXIT_CODES.TIMEOUT,
  RATE_LIMITED: EXIT_CODES.ERROR,
  CONFIG_ERROR: EXIT_CODES.CONFIG_ERROR,
  NOT_IMPLEMENTED: EXIT_CODES.ERROR,
  UNKNOWN_ERROR: EXIT_CODES.ERROR,
};
